print("Welcome to the tip calculator!")
bill = float(input("What was the total bill? $"))
tip = int(input("What percent tip would you like to give, 10, 12, or 15 percent? "))
no_ppl = int(input("How many people to split the bill? "))
total = bill * (1 + tip / 100)
total_pp = round(total / no_ppl, 2)
print(f"Each person should pay: ${total_pp}")
